# Generated by Django 5.2.6 on 2025-09-06 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=250)),
                ('details', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GovtStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('buy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.buy')),
            ],
        ),
        migrations.CreateModel(
            name='BuyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.buy')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.requestrationcard')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.requestrationcard')),
                ('staff_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.govtstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiloorlitter', models.CharField(max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.product')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='RationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.requestrationcard')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiloorlitter', models.CharField(max_length=100)),
                ('forthemonth', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.product')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.type')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('hname', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('hno', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='TimeAllocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='requestrationcard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.user'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartrationapp.user'),
        ),
    ]
